server:
  port: 9011

## Database config
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.10.233:1521:ORCLCDB
    username: smb_um
    password: smb_um4321
    driver-class-name: oracle.jdbc.OracleDriver

  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://192.168.10.230:9001}/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    #    metadataMap:
    #      instanceId: ${spring.application.name}:${spring.application.instance_id:8011}
    instanceId: ${spring.application.name}:${spring.application.instance_id:9011}

